catalog/urls.py
from django.urls import path
from catalog.views import home, contact, product_1
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name="home"),
    path('contact/', contact, name="contact"),
    path('product_1/<int:pk>', product_1, name="product_1")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='product/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')

    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.name}, {self.category}, {self.price}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('price',)

catalog/views.py
from django.shortcuts import render

from catalog.models import Product, Category


def home(request):
    context = {
        'objects_list': Product.objects.all()
    }
    return render(request, 'catalog_app/home.html', context)


def contact(request):
    return render(request, 'catalog_app/contact.html')


def product_1(request, pk):
    context = {
        'object': Product.objects.get(pk=pk)
    }
    return render(request, 'catalog_app/product_1.html', context)

catalog/templates/catalog_app/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Идейка!</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-xxl">



        <br>
        <div class="row text-center">
            <div class="col-sm-2">

                {% include 'catalog_app/includes/inc_base.html' %}

            </div>
            <div class="col-sm-7">

            </div>
            <div class="col-sm-3">
                <em>Закажите <strong>идею</strong> сейчас, и уже сегодня она посетит вашу голову!</em>
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock %}


    <div class="container-xxl">
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <br>
        <div class="row">
            <div class="col-12 col-md">
                "Идейка!"
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Общая информация</a></li>
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>

            <div class="col-6 col-md">
                <h5><a class="text-muted" href="#">Оплата</a></h5>

            </div>
            <div class="col-6 col-md">
                <h5><a class="text-muted" href="#">Доставка</a></h5>

            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Анализ проблемы по телефону</a></li>
                    <li><a class="text-muted" href="#">Выезд специалиста на место</a></li>
                </ul>
            </div>

        </div>
    </footer>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

catalog/templates/catalog_app/blank.html
{% extends 'catalog_app/base.html' %}

{% block content %}
<h1 class="text-center">Название товара</h1>
<div class="container">
    <br>
    <div class="row">
        <div class="col-3">
            <div class="card text-center" style="width: 18rem;">
                <img src="/media/product/Заглушка.jpeg" class="card-img-top" alt="...">
                <div class="card-body">
                <p class="card-text">Краткое описание товара</p>
                <h3 class="card-text">Цена</h3>

                <a href="#" class="btn btn-primary">В корзину</a>
                </div>
            </div>
        </div>
        <div  class="col-9">
            <ul class="list">
                <li>Тезис, описывающий плюсы или минусы товара</li>
                <li>Второй тезис, описывающий плюсы или минусы товара</li>
                <li>Третий тезис, описывающий плюсы или минусы товара</li>
                <li>Четвертый тезис, описывающий плюсы или минусы товара</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog_app/contact.html
{% extends 'catalog_app/base.html' %}

{% block content %}

    <div class="container-xxl">
        <div class="row">
            <div class="col-sm-2">

            </div>
            <div class="col-sm-7">
                <div class="card">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Страна</li>
                        <li class="list-group-item">ИНН</li>
                        <li class="list-group-item">Адрес</li>
                    </ul>
                </div>
            </div>
            <div class="col-3">
                <div class="card">
                    <div class="card-header">
                        Связаться с нами
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="mb-3">
                                <label class="form-label">Имя</label>
                                <input type="text" name="name" class="form-control">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Номер телефона</label>
                                <input type="text" name="phone number" class="form-control">
                            </div>


                            <div class="mb-3">
                                <label class="form-label">Сообщение</label>
                                <textarea name="message" class="form-control"></textarea>
                            </div>

                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

catalog/templates/catalog_app/home.html
{% extends 'catalog_app/base.html' %}

{% block content %}


<h1 class="text-center">Интернет-магазин "Идейка!"</h1>
<h3 class="text-center"><em>От хорошей идеи до гениальной всего 50$!</em></h3>
    <div class="container-xxl">
        <div class="row">
            {% for object in objects_list %}
            <div class="col">
                <div class="card text-center">
                    <div class="card-header">
                        {{object.name}}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{object.price}}$</h5>
                        <p class="card-text">{{object.description|slice:":100" }}</p>

                        <a href="{% url 'catalog:product_1' object.pk %}" class="btn btn-primary">Купить</a>

                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

catalog/templates/catalog_app/includes/inc_base.html
<a class="p-l-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
<a class="p-l-2 btn btn-outline-primary" href="{% url 'catalog:contact' %}">Контакты</a>

catalog/templates/catalog_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog</title>
</head>
<body>
    <h1>Catalog</h1>
</body>
</html>

catalog/templates/catalog_app/product.html
{% extends 'catalog_app/base.html' %}

{% block content %}
<h1 class="text-center">Так себе идейка...</h1>
<div class="container">
    <br>
    <div class="row">
        <div class="col-3">
            <div class="card text-center" style="width: 18rem;">
                <img src="/media/product/Идея.jpeg" class="card-img-top" alt="...">
                <div class="card-body">
                <p class="card-text">Идея средней паршивости, зато не придется снимать последние штаны.</p>
                <h3 class="card-text">30$</h3>

                <a href="#" class="btn btn-primary">В корзину</a>
                </div>
            </div>
        </div>
        <div  class="col-9">
            <ul class="list">
                <li>Не смотря на то, что данная идея сгенерирована, мягко говоря,
                    не самыми нашими лучшими специалистами,<br>Вы останетесь довольны(не такие уж они
                    не самые лучшие).</li>
                <li>Если Вас не устроил результат, не отчаивайтесь, можно попробовать
                    еще раз и еще...<br>Благо, цена позволяет!</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog_app/product_1.html
{% extends 'catalog_app/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="text-center">{{object.name}}</h1>
<div class="container">
    <br>
    <div class="row">
        <div class="col-3">
            <div class="card text-center" style="width: 18rem;">
                <img src="{{ object.image|my_media }}" class="card-img-top" alt="...">
                <div class="card-body">
                <p class="card-text">{{object.description}}</p>
                <h3 class="card-text">{{object.price}}$</h3>

                <a href="#" class="btn btn-primary">В корзину</a>
                </div>
            </div>
        </div>
        <div  class="col-9">
            <ul class="list">
                <li><span style="font-size: 20px">Тезис с описанием плюсов или минусов товара.</span></li>
                <li><span style="font-size: 20px">Второй тезис с описанием плюсов или минусов товара.</span></li>
                <li><span style="font-size: 20px">Третий тезис с описанием плюсов или минусов товара.</span></li>
                <li><span style="font-size: 20px">И еще один тезис с описанием плюсов или минусов товара.</span></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}